spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/local_events_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

jwt.secret=80wpbFTpE6NH5AZufuSydqGfnzogpR1r8HyPJCAmYJ
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

cloudinary.api-key=476742214359912
cloudinary.api-secret=EqJbmozdJQp_sm2O8PMFPmGpIs0